// ── Glossary data ─────────────────────────────────────────────────────────────
// Single source of truth for all variable descriptions shown ONLY on the GLOSSARY page.

export type GlossaryCategory =
  | 'PROGRESSION'
  | 'DANGEROUSNESS'
  | 'RECEPTION'
  | 'GRAVITY'
  | 'DECISION_QUALITY';

export interface GlossaryEntry {
  label: string;
  description: string;
}

export interface GlossarySection {
  category: GlossaryCategory;
  title: string;
  color: string;
  intro: string;
  entries: GlossaryEntry[];
}

export const GLOSSARY_SECTIONS: GlossarySection[] = [
  {
    category: 'PROGRESSION',
    title: 'Progression',
    color: '#16a34a',
    intro:
      'A composite index measuring how effectively the player advances the ball through opposing lines: progressive passing volume, passing accuracy into dangerous zones, and progressive carries. Scale 0–100, the mean of within-role percentiles across progressive metrics from Wyscout (Progressive passes/90, Accurate progressive passes %, Passes to final third/90, Passes to penalty area/90, Progressive runs/90). Evaluated strictly within the player\'s macro-role.',
    entries: [
      { label: 'LB Geom /90',                 description: 'Progressive passes per 90 minutes from Wyscout (Progressive passes/90). The rate at which the player breaks through opposing pressure with forward passes.' },
      { label: 'LB Quality /90',              description: 'Accurate progressive passes per 90 minutes (Progressive passes/90 × Accurate progressive passes %). Combines forward ambition with execution accuracy.' },
      { label: 'LB EPV /90',                  description: 'Passes to the final third per 90 minutes from Wyscout (Passes to final third/90). Measures frequency of successfully delivering the ball into dangerous attacking territory.' },
      { label: 'Hull Penetr. /90',            description: 'Completed passes into the opponent penalty box per 90 minutes (Passes to penalty area/90 × pass accuracy %). Measures successful box penetrations.' },
      { label: 'Def. Bypassed Avg',           description: 'Progressive runs per 90 minutes from Wyscout (Progressive runs/90). Measures dynamic forward ball carries that advance the ball towards the opponent goal.' },
      { label: 'Def. Bypassed (avg)',         description: 'Progressive runs per 90 minutes from Wyscout (Progressive runs/90). Total dynamic forward ball carries.' },
      { label: 'LB Geom',                     description: 'Total count of progressive passes advancing the ball towards the opposing goal (Progressive passes/90 × minutes / 90).' },
      { label: 'LB Quality',                  description: 'Total count of accurate progressive passes successfully completed forward.' },
      { label: 'High Value Pass',             description: 'Total passes delivered into the final third across all matches played (Passes to final third/90 × minutes / 90).' },
      { label: 'Penetration Attempts (n)',    description: 'Total passes attempted into the opponent penalty box across the tournament (Passes to penalty area/90 × minutes / 90).' },
      { label: 'Successful Penetrations (n)', description: 'Estimated completed passes into the opponent penalty box.' },
      { label: 'Penetration Attempts /90',    description: 'Passes into the opponent penalty box attempted per 90 minutes from Wyscout (Passes to penalty area/90). Direct vertical box delivery ambition.' },
      { label: 'Successful Penetrations /90', description: 'Completed passes into the opponent penalty box per 90 minutes.' },
      { label: 'LB Geom %',                   description: 'Share of total passes that are progressive (Progressive passes/90 divided by total passes/90 × 100).' },
      { label: 'LB Quality %',                description: 'Share of total passes that are accurate progressive passes.' },
      { label: 'LB EPV %',                    description: 'Share of total passes directed into the final third.' },
      { label: 'Penetration Completion %',    description: 'Accuracy percentage of passes directed into the opponent penalty box.' },
    ],
  },
  {
    category: 'DANGEROUSNESS',
    title: 'Dangerousness',
    color: '#dc2626',
    intro:
      'A magnitude index of total offensive threat generated by the player in possession. Scale 0–100, evaluated as the within-role percentile of composite Expected Possession Value per 90 (sum of Wyscout metrics: Expected goals/90, Expected assists/90, Key passes/90, and Touches in box/90). Evaluated strictly within the player\'s macro-role.',
    entries: [
      { label: 'EPV Added /90',           description: 'Total offensive threat generated per 90 minutes (sum of xG/90, xA/90, key passes/90, and box touches/90 from Wyscout). The headline Dangerousness index is the within-role percentile of this value.' },
      { label: 'EPV Penetr. /90',         description: 'Expected goals per 90 minutes from Wyscout (Expected goals/90). Measures direct scoring threat and finishing quality.' },
      { label: 'EPV In-Circ /90',         description: 'Expected assists per 90 minutes from Wyscout (Expected assists/90). Measures the creation of high-probability scoring chances for teammates.' },
      { label: 'EPV Exit /90',            description: 'Key passes per 90 minutes from Wyscout (Key passes/90). Measures decisive passes directly leading to a teammate shot attempt.' },
      { label: 'EPV Out-Circ /90',        description: 'Touches in the opponent penalty box per 90 minutes from Wyscout (Touches in box/90). Captures offensive presence in high-threat locations.' },
      { label: 'EPV Penetr. (sum)',       description: 'Total Expected Goals (xG) accumulated by the player across the tournament (Expected goals/90 × minutes / 90).' },
      { label: 'EPV In-Circ (sum)',       description: 'Total Expected Assists (xA) accumulated by the player across the tournament (Expected assists/90 × minutes / 90).' },
      { label: 'EPV Exit (sum)',          description: 'Total key passes delivered across all matches played (Key passes/90 × minutes / 90).' },
      { label: 'EPV Out-Circ (sum)',      description: 'Total touches recorded in the opponent penalty box (Touches in box/90 × minutes / 90).' },
    ],
  },
  {
    category: 'RECEPTION',
    title: 'Reception',
    color: '#2563eb',
    intro:
      'A composite index measuring a player\'s presence and execution in congested attacking territory: touches in the penalty area, received passes in build-up, and deep completions into compressed blocks. Scale 0–100, the mean of within-role percentiles of Wyscout metrics: Touches in box/90, Received passes/90, and Deep completions/90. Evaluated strictly within macro-role.',
    entries: [
      { label: 'Between Lines %',     description: 'Touches in the penalty box as a share of total passes (Touches in box/90 divided by Passes/90 × 100), capturing high-danger zone positioning.' },
      { label: 'Between Lines /90',   description: 'Touches in the opponent penalty box per 90 minutes from Wyscout (Touches in box/90). Quantifies operating in congested areas.' },
      { label: 'Hull Exits /90',      description: 'Received passes per 90 minutes from Wyscout (Received passes/90). Measures a player\'s availability to teammates and secure ball reception during possession build-up.' },
      { label: 'In-Circ /90',         description: 'Rate of received passes per 90 minutes from Wyscout (Received passes/90).' },
      { label: 'Press. Resist %',     description: 'Deep completions within-role percentile from Wyscout (Deep completions/90). Deliveries completed into tight, compressed defensive blocks.' },
      { label: 'Block Receipts (n)',  description: 'Total touches recorded in the opponent penalty box across all matches played (Touches in box/90 × minutes / 90).' },
      { label: 'Press. Resist (n)',   description: 'Total deep completions completed across all matches played (Deep completions/90 × minutes / 90).' },
      { label: 'In-Circ (n)',         description: 'Total received passes accumulated across all matches played (Received passes/90 × minutes / 90).' },
      { label: 'Hull Exits %',        description: 'Accurate pass percentage from Wyscout (Accurate passes, %), reflecting secure ball distribution after receiving.' },
    ],
  },
  {
    category: 'GRAVITY',
    title: 'Gravity',
    color: '#d97706',
    intro:
      'An exploratory tactical index evaluating how much defensive attention a player commands from opponents. Scale 0–100, calculated as the within-role mean percentile of Wyscout metrics: Fouls suffered/90 and Offensive duels/90. Evaluated strictly within macro-role.',
    entries: [
      { label: 'Space Attraction %', description: 'Within-role percentile of Fouls suffered per 90 from Wyscout (Fouls suffered/90). Evaluates how often opponents commit fouls to stop the player\'s progression.' },
      { label: 'Gravity Hull %',     description: 'Within-role percentile of Offensive duels per 90 from Wyscout (Offensive duels/90). Measures how frequently defenders are pulled into 1v1 individual contests against the player.' },
      { label: 'Def. Pull |m|',      description: 'Composite directional gravity score (mean percentile of Fouls suffered/90 and Offensive duels/90), quantifying total defensive disruption and attention commanded.' },
      { label: 'Def. Pull (m)',      description: 'Directional gravity score derived from fouls suffered percentile deviation from median. Captures relative defensive attraction.' },
    ],
  },
  {
    category: 'DECISION_QUALITY',
    title: 'Decision Quality',
    color: '#7c3aed',
    intro:
      'A composite model evaluating technical decision execution, ball security, and calculated risk-taking in possession using high-density Wyscout metrics from wyscout_sample.csv. The headline Decision Quality Index (DQI) is a within macro-role percentile from 0 to 100: 100 means the best decision quality profile in the role, 50 the median. The index synthesizes four tactical pillars: Possession Accuracy, Duel Robustness, Risk Readings per 90, and Risk Accuracy.',
    entries: [
      { label: 'Possession Accuracy',   description: 'Percentage of passes completed accurately in open play from Wyscout (Accurate passes, %). Reflects baseline decision reliability and pass execution under pressure.' },
      { label: 'Possession Accuracy %', description: 'Percentage of passes completed accurately in open play from Wyscout (Accurate passes, %). Reflects baseline decision reliability and pass execution under pressure.' },
      { label: 'Duel Robustness',       description: 'Percentage of ground and aerial duels won from Wyscout (Duels won, %). Evaluates physical and technical execution when challenging opponents or protecting the ball.' },
      { label: 'Duel Robustness %',     description: 'Percentage of ground and aerial duels won from Wyscout (Duels won, %). Evaluates physical and technical execution when challenging opponents or protecting the ball.' },
      { label: 'Risk Readings / 90',    description: 'Rate of incisive actions attempted per 90 minutes (sum of Key passes/90 and Smart passes/90 from Wyscout). Captures vertical ambition and willingness to take proactive risks.' },
      { label: 'Risk Readings /90',     description: 'Rate of incisive actions attempted per 90 minutes (sum of Key passes/90 and Smart passes/90 from Wyscout). Captures vertical ambition and willingness to take proactive risks.' },
      { label: 'Risk Accuracy',         description: 'Accuracy percentage on progressive passes from Wyscout (Accurate progressive passes, %). Measures how cleanly the player delivers high-risk, forward-advancing passes into dangerous zones.' },
      { label: 'Risk Accuracy %',       description: 'Accuracy percentage on progressive passes from Wyscout (Accurate progressive passes, %). Measures how cleanly the player delivers high-risk, forward-advancing passes into dangerous zones.' },
      { label: 'Value Impact',          description: 'Within-role percentile ranking of offensive danger created (mean percentile of Expected goals/90 and Expected assists/90 from Wyscout). Directly reflects the tangible scoring impact generated by the player\'s decisions.' },
      { label: 'Score',                 description: 'The normalized composite score behind the Decision Quality Index (0 to 1). Shown for analytical transparency.' },
      { label: 'Score (DQI)',           description: 'The normalized composite score behind the Decision Quality Index (DQI), ranging from 0 to 1.' },
      { label: 'Decisions Analysed',    description: 'Total passes recorded for the player across the tournament (Passes/90 × minutes / 90).' },
    ],
  },
];

// Colour map for index badges on the glossary page
export const INDEX_COLORS: Record<string, string> = {
  PROGRESSION:      '#16a34a',
  DANGEROUSNESS:    '#dc2626',
  RECEPTION:        '#2563eb',
  GRAVITY:          '#d97706',
  DECISION_QUALITY: '#7c3aed',
};